web/router.ex
defmodule Pwc.Router do
  use Pwc.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pwc.FetchPeerInfo
  end

  pipeline :admin do
    plug Pwc.AdminFirewall
  end

  scope "/", Pwc do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/login", AuthenticationController, :show
    post "/login", AuthenticationController, :login
    get "/logout", AuthenticationController, :logout

    scope "/admin" do
      pipe_through :admin

      get "/neighbors", NeighborController, :index
      resources "/users", UserController
    end
  end
end

web/views/layout_view.ex
defmodule Pwc.LayoutView do
  use Pwc.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>6co</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container-fluid">
      <header>
        <nav role="navigation" class="navbar">
          <a class="navbar-brand navbar-left" href="<%= page_path(@conn, :index) %>">
            <img alt="Brand" class="logo" src="/images/6co.png">
          </a>
          <%= if @is_admin do %>
            <ul class="nav nav-pills navbar-right">
              <li style="padding: 10px 15px;">Administration</li>
              <li><a href="<%= neighbor_path(@conn, :index) %>">Stations connectées</a></li>
              <li><a href="<%= user_path(@conn, :index) %>">Utilisateurs enregistrés</a></li>
            </ul>
          <% else %>
            <ul class="nav nav-pills navbar-right">
              <%= if ! @remote_allowed do %>
                <li><a href="<%= authentication_path(@conn, :login) %>">Connexion</a></li>
              <% else %>
                <li><a href="<%= authentication_path(@conn, :logout) %>">Déconnexion</a></li>
              <% end %>
            </ul>
          <% end %>
        </nav>

      </header>

      <div class="clearfix"></div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

      <div><br></div>

      <footer class="text-center text-muted">

      </footer>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>